spring:
  application:
    name: inventory-api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/product/**


server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka